default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: railsuser
  password: ":LK:LK111"

development:
  <<: *default
  database: purchased_book_app_development

test:
  <<: *default
  database: purchased_book_app_test

production:
  <<: *default
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  url: <%= ENV['DATABASE_URL'] %>
  host: <%= ENV['DB_HOSTNAME'] %>
